# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.define "database" do |server|
    server.vm.network :private_network, ip:"192.168.33.10"
    server.vm.box = "viniciusfs/centos7"
    server.vm.provision :shell, :inline => install_mariadb
    server.vm.provision :shell, :inline => setup_database
    server.vm.provision :shell, :inline => setup_firewall
  end
end

def install_mariadb
  <<-'MARIADB'
if ! [ $(which mysql) ]; then
  echo Install mariadb ...
  yum -y install mariadb-server mariadb
  systemctl start mariadb
  systemctl enable mariadb
  echo -ne "
    \n
    Y
    Password
    Password
    Y
    Y
    Y
    Y
  " | mysql_secure_installation
else
  echo Skip install mariadb ...
fi
  MARIADB
end

def setup_database
  <<-'SETUP'
echo Setup database ...
mysql -uroot -pPassword < /vagrant/bbs.sql
  SETUP
end

def setup_firewall
  <<-'FIREWALL'
echo Setup firewall ...
systemctl enable firewalld
systemctl start firewalld
firewall-cmd --add-service=mysql --permanent
firewall-cmd --reload
  FIREWALL
end

